# Generated by Django 4.2.27 on 2026-01-03 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('HQ', 'HQ'), ('Youth Ministry', 'Youth Ministry'), ('BOT', 'BOT'), ('GOQ', 'GOQ'), ('Men of Integrity', 'Men of Integrity'), ('Go-Quickly', 'Go-Quickly'), ('Child Evangelism', 'Child Evangelism'), ("Apostle's Update Team", "Apostle's Update Team"), ('FABM Team', 'FABM Team')], default='HQ', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
