# Generated by Django 4.2.27 on 2026-01-04 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyevent',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='historyevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Specific date of the event'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year of the event (e.g. 1990)', null=True),
        ),
    ]
