# Generated by Django 4.2.27 on 2026-01-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Healing', 'Healing'), ('Family', 'Family'), ('Employment', 'Employment'), ('Spiritual Growth', 'Spiritual Growth'), ('Health', 'Health'), ('Guidance', 'Guidance'), ('Other', 'Other')], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_viral', models.BooleanField(default=False)),
            ],
        ),
    ]
