# Generated by Django 4.2.27 on 2026-01-03 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('video', 'Video'), ('announcement', 'Announcement'), ('newsletter', 'Newsletter'), ('gallery', 'Gallery'), ('apostle', "Apostle's Update")], max_length=50)),
                ('image', models.ImageField(upload_to='updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.CharField(choices=[('MEDIA TEAM', 'MEDIA TEAM'), ('HQ TEAM', 'HQ TEAM'), ('ADMIN', 'ADMIN')], default='HQ TEAM', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
