# Generated by Django 4.2.27 on 2026-01-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='team',
            field=models.CharField(choices=[('HQ', 'HQ'), ('Youth Ministry', 'Youth Ministry'), ('BOT', 'BOT'), ('GOQ', 'GOQ'), ('Men of Integrity', 'Men of Integrity'), ('Go-Quickly', 'Go-Quickly'), ('Child Evangelism', 'Child Evangelism'), ("Apostle's Update Team", "Apostle's Update Team"), ('FABM Team', 'FABM Team')], default='HQ', max_length=100),
        ),
    ]
