# Generated by Django 4.2.27 on 2026-01-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_alter_update_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
