# Generated by Django 4.2.27 on 2026-01-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_update_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='update',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('review', 'Resent for Review'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
